### ISSUE TITLE
Git分支-分支的衍合，翻译错误

### ISSUE THREAD

**Issue by pupie** [iissnan/progit#1]
Figure 3-31. A history with a topic branch off another topic branch.

Suppose you decide that you want to merge your client-side changes into your mainline for a release, but you want to hold off on the server-side changes until it’s tested further. You can take the changes on client that aren’t on server (C8 and C9) and replay them on your master branch by using the --onto option of git rebase:

图 3-31. 从一个特性分支里再分出一个特性分支的历史。

假设在接下来的一次软件发布中，我们决定先把客户端的修改并到主线中，而暂缓并入服务端软件的修改（因为还需要进一步测试）。这个时候，我们就可以把基于 server 分支而非 master 分支的改变（即 C8 和 C9），跳过 server 直接放到 master 分支中重演一遍，但这需要用 git rebase 的 --onto 选项指定新的基底分支 master。

“我们就可以把基于server分支而非master分支” 应该改为“client分支而非server分支”

源文件已修改：
https://github.com/progit/progit/blob/master/zh/03-git-branching/01-chapter3.markdown

最新中文翻译已更新，建议重新生成页面

**Comment by iissnan** [comment]
已重新生成。

感谢反馈！:smile:
